#!/bin/sh

MRTG_TMP_DIR=/tmp/mrtg/
MRTG_TMP_FILE=load.tmp

/bin/mkdir -p -m0755 $MRTG_TMP_DIR
/usr/bin/touch $MRTG_TMP_DIR$MRTG_TMP_FILE

echo `LC_ALL=C /usr/bin/uptime | perl -ne '@F = /^\s*\S+\s+up\s+([^,]+,[^,]+),.+load averages: ([0-9.]+), ([0-9.]+), ([0-9.]+)/; print $F[1]*100;'` > $MRTG_TMP_DIR$MRTG_TMP_FILE
echo `LC_ALL=C /usr/bin/uptime | perl -ne '@F = /^\s*\S+\s+up\s+([^,]+,[^,]+),.+load averages: ([0-9.]+), ([0-9.]+), ([0-9.]+)/; print $F[3]*100;'` >> $MRTG_TMP_DIR$MRTG_TMP_FILE
echo `/usr/bin/uptime | grep -o 'up.*' | sed -e 's/up //' -e 's/, [0-9] user.*//g'` >> $MRTG_TMP_DIR$MRTG_TMP_FILE
echo `/bin/hostname` >> $MRTG_TMP_DIR$MRTG_TMP_FILE

cat $MRTG_TMP_DIR$MRTG_TMP_FILE

exit 0
